config/routes.rb
Rails.application.routes.draw do

  resources :friendships, except: :create
  post '/friendships', to: "friendships#create", as: "create_friendship"

  devise_for :users
  authenticated :user do
    root 'welcome#index'
  end

    unauthenticated :user do
    devise_scope :user do
      get "/" => "welcome#index"
    end
  end

  resources :conversations do
    resources :messages
  end
  resources :users do
    resources :reviews
  end

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  get "welcome/index"

  get "welcome/go_premium"

  get "welcome/blog"

end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable
    has_many :conversations, :foreign_key => :sender_id
    has_many :reviews
    

	# uncomment this when the form is ready for uploading image
	mount_uploader :avatar, AvatarUploader
	geocoded_by :address
  	after_validation :geocode 

  	
  	has_many :friendships
    has_many :passive_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
     has_many :active_friends, -> { where(friendships: { approved: true}) }, :through => :friendships, :source => :friend
    has_many :passive_friends, -> { where(friendships: { approved: true}) }, :through => :passive_friendships, :source => :user
    has_many :pending_friends, -> { where(friendships: { approved: false}) }, :through => :friendships, :source => :friend
    has_many :requested_friendships, -> { where(friendships: { approved: false}) }, :through => :passive_friendships, :source => :user


  	#this will allow you to have a form with multiple input that will allow you to search 
 #  	def address
 #  		[street, city, state, country].compact.join(', ')
	# end
	def self.average_rating(id)
		@reviews = Review.where(user_id: id)
		@reviews.count == 0 ? 0 : @reviews.average(:star).round(2)
	end
   

    def friends
      active_friends | passive_friends
    end
  	

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    if params[:search].present?
      if current_user
        @users = User.near(params[:search], 100).where.not("id = ?",current_user.id).order("created_at DESC")
      else
        @users = User.all
      end
      @hash = Gmaps4rails.build_markers(@users) do |user, marker|
        marker.lat user.latitude
        marker.lng user.longitude
        marker.infowindow user.first_name
      end
      @header = "Locals Nearby"
    else
      @user = User.all
      if current_user
        @users = User.where.not("id = ?",current_user.id).order("created_at DESC")
      else
        @users = User.all
      end
      @user_locs = @users.where.not(latitude: nil)
      @hash = Gmaps4rails.build_markers(@user_locs) do |user, marker|
        marker.lat user.latitude
        marker.lng user.longitude
        marker.infowindow [user.first_name, user.last_name].join(" ")
      end
      @header = "Connect with Locals"
    end
    if current_user
      @conversations = Conversation.involving(current_user).order("created_at DESC")
    end
  end
    
  def edit
    @user = current_user
    @user.geocode
  end

  def show
    @user = User.find(params[:id])
    @user_friends = []
    @user.friendships.where(approved: true).each do |friendship|
      
      friend = User.find(friendship.friend_id)
      @user_friends << friend
    end
    #user_friends is an array of all the approved friends

    @user_friends = @user_friends.uniq

    # @requested_friends =[]
    # @user.friendships.where(approved: false).each do |friendship|
      
    #   friend = User.find(friendship.friend_id)
    #   @requested_friends << friend
    # end
    # #requested friends is the friends that the current user has requested but they have not accepted
    # @requested_friends = @requested_friends.uniq
  
    @reviews = @user.reviews
    @review = Review.new
    if current_user
      @conversations = Conversation.involving(current_user).order("created_at DESC")
    end  

    @hash = Gmaps4rails.build_markers(@user_friends) do |user, marker|
        marker.lat user.latitude
        marker.lng user.longitude
        marker.infowindow [user.first_name, user.last_name].join(" ")
      end
  end

  def address
    current_user.location 
  end

  def update
    @user = current_user
    @user.geocode
    if @user.update_attributes(user_from_params)
      redirect_to "/users/#{@user.id}#profile"
    else
      render 'edit'
    end
  end

  def delete
  end

  def show_nearby_locations
    @nearbys = User.near("#{params[:address]}", 5,:order => "distance",:units => :km)
    @nearbys.first(10)
  end


  private

  def user_from_params
    params.require(:user).permit(:first_name, :last_name, :email, :avatar, :birthdate, :location, :bio, :interests, :emer_contact, :emer_phone, :emer_first, :emer_last, :emer_relation, :emer_address, :latitude, :longitude, :address)
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def conversation_interlocutor(conversation)
    conversation.recipient == current_user ? conversation.sender : conversation.recipient
  end
end

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :first_name %>
  <%= form.text_field :first_name %>
</div>

<div class="text-field">
  <%= form.label :last_name %>
  <%= form.text_field :last_name %>
</div>

<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %> 
</div>

app/views/users/back_up.html.erb
<h2 id="title"><%=@user.first_name %> 
<%= @user.last_name %></h2>
<p><strong>Email: </strong> <%=@user.email %> </p>
<p> <%=@user.address%> <%= @user.latitude %>
	<%= @user.longitude %></p>

<div class="row">
      <div class="col-md-12">
            <p class="text-center">Copyright © Local Host Ltd 2016 & Next Academy</p>
      </div>
</div>


<% if @user.nearbys(100) %>
	<% @user.nearbys(100).all.each do |location| %>
	  <li><%= link_to location.address, location %> (<%= location.distance.round(2) %> miles)</li>
	<% end %>
<% end %>

<% unless current_user == @user %>
    <%= link_to "Add Friend", friendships_path(:friend_id => @user.id), :method => :post %>
<% end %>

<h4>Friends</h4>
<ul>
    <% @user.friends.each do |friend| %>
    <li>
      <%= friend.first_name %> <%= friend.last_name %>
      <% if current_user == @user %>
        <%= link_to "Remove", friendship_path(friend.id), :method => :delete %>
      <% end %>
    </li>
  <% end %>
</ul>

<% if current_user == @user %>
    <h4>Friend Requests</h4>
    <ul>
        <% @user.requested_friendships.each do |request| %>
        <li>
          <%= request.first_name %> <%= request.last_name %> 
          <%= link_to "Accept", friendship_path(request.id), :method => "put" %> 
          <%= link_to "Decline", friendship_path(request.id), :method => :delete %>
        </li>
      <% end %>
    </ul>
<% end %>


<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@user.latitude}%2C#{@user.longitude}" %>

<%= link_to "edit profile", edit_user_path %>

<%= link_to "All users", users_path %>


<div class="container">
      <div class="row">
            <div class="col-md-4">
                  <div class="contact-cards">
                        <div class="row">
                              <div class="col-xs-5">
                                    <img src="http://bootdey.com/img/Content/user_1.jpg" alt=""  class="img-responsive"/>
                              </div>
                              <div class="col-xs-7 removePadding">
                                    <h3>
                                          Munna JS
                                    </h3>
                                    <p>
                                          munna.js@3mdigital.co.in<br>
                                          9999999999
                                    </p>
                                    <button class="btn btn-warning">Call Now</button>
                              </div>
                        </div>
                  </div>
            </div>
            <div class="col-md-4">
                  <div class="contact-cards">
                        <div class="row">
                              <div class="col-xs-5">
                                    <img src="http://bootdey.com/img/Content/user_2.jpg" alt=""  class="img-responsive"/>
                              </div>
                              <div class="col-xs-7 removePadding">
                                    <h3>
                                          Munni PHP
                                    </h3>
                                    <p>
                                          Munni.php@3mdigital.co.in<br>
                                          9999999999
                                    </p>
                                    <button class="btn btn-warning">Call Now</button>
                              </div>
                        </div>
                  </div>
            </div>
            <div class="col-md-4">
                  <div class="contact-cards">
                        <div class="row">
                              <div class="col-xs-5">
                                    <img src="http://bootdey.com/img/Content/user_3.jpg" alt=""  class="img-responsive"/>
                              </div>
                              <div class="col-xs-7 removePadding">
                                    <h3>
                                          Munna CSS
                                    </h3>
                                    <p>
                                          munna.css@3mdigital.co.in<br>
                                          9999999999
                                    </p>
                                    <button class="btn btn-warning">Call Now</button>
                              </div>
                        </div>
                  </div>
            </div>
      </div>
      <div class="row">
            <div class="col-md-12">
                  <p class="text-center">Copyright © Local Host Ltd 2016 & Next Academy</p>
            </div>
      </div>
</div>

app/views/users/blog.html.erb
<center>
<h1 id="title">Blog<h1>

</center>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/index.html.erb
<html>
<head>      
</head>
<body>
 <div class="Container1">
      <div class="find-users" style="text-align: center">
      <h1 id="title"> <%=@header%> </h1>
      <br>
      </div>
      <div class="Content">
        <div class="Wrapper">
          
            <div class="col-md-6 LeftContent" style=" height: 97%;">
              <% @users.each do |user|%>
                   <div class="contact-cards-index-page">
                    <div class="row" >
                        <div class="col-xs-3" >
                            
                              <%=image_tag user.avatar, class: "img-responsive" %>
                        </div>
                        <div class="col-xs-6" style='padding-left: 5px;' >
                              <h3 style='margin: 0px;' >
                                    <%= link_to [user.first_name, user.last_name].join(" "), user_path(user.id) %>
                                    
                              </h3>
                                <p>
                                Currently in: <%= user.address %><br>
                                Interests: <%= user.interests %><br>
                                Local Hacks: <%= user.tips %><br>
                                Favourite Destinations: <%= user.faves %>
                                </p>
                            
                        </div>
                        <div class="col-xs-3 removePadding" style='text-align: right;'>
                          <% if current_user %>
                            <%= link_to "             View Profile           ", user_path(user.id), class: "btn btn-success btn-xs"  %>
                            <br>
                             <%= link_to "Add Friend", friendships_path(:friend_id => user.id), :method => :post, class: "btn btn-success btn-xs"  %>
                            <br>
                             <%= link_to "Send Message", "#", class: "btn btn-success btn-xs start-conversation", "data-sid" => current_user.id, "data-rip" => user.id %> 
                          <%else%>
                              <%= link_to " Login to View", "/users/sign_in", class: "btn btn-success btn-xs"  %>
                          <%end%>
                        </div>
                      </div>
                  </div>
                <%end%> 
                 
            </div>
        <div class="col-md-6 right">
          <!-- Your second column here -->
          <div style='width: 100%; height: 100%; '>
            <div id="map" style='width: 100%; height: 97%;'></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: "map"}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });
  </script>
</body>
</html>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="container ">
   <h1 class="text-center" id="title"><%= @user.first_name %> <%= @user.last_name %></h1>
   <div class="nav-center" style="height: 30px;">
      <ul class="nav-profile nav-pills">
         <% if current_user == @user %>
         <li><a href="#profile" id="targeted" >Profile</a></li>
         <li><a href="#edit_profile">Edit Profile</a></li>
         <li><a href="#friends">Friends</a></li>
         <% unless %>
         <li><a href="#reviews">Reviews</a></li>
         <% end %>
         <% else %>
         <li><a href="#profile" id="targeted" >Profile</a></li>
         <li><%= link_to "Add Friend", friendships_path(:friend_id => @user.id), :method => :post %></li>
         <li><a href="#reviews">Reviews</a></li>
         <li><%= link_to "Send Message", "#", "data-sid" => current_user.id, "data-rip" => @user.id %></li>
         <% end %>
     </ul>
 </div>
 <div class="main">
  <div class="mainContent clearfix">
     <div id="profile" class="logo-avatar">
        <a href=""><img class="pic img-cricle" src="<%=@user.avatar%>" alt="profile_pic"></a>
        <div class="monitor" style="width: 1000px; margin-top: 350px;height: initial; float:none;">
           <h4>Bio</h4>
           <p><%= @user.bio %></p>
           <h4>Interest</h4>
           <p><%= @user.interests %></p>
           <h4>Birthday</h4>
           <p><%= @user.birthdate %></p>
           <h4>Location</h4>
           <p><%= @user.address%></p>
       </div>
   </div>
   <div id="edit_profile">      
      <ul class="content">
         <div class='row'>
            <% if @user.errors.any? %>
            <ul>
               <% @user.errors.full_messages.each do |message| %>
               <li><%= message %></li>
               <% end %>
           </ul>
           <% end %>
       </div>
       <div class="row">
          <section>
             <div class="wizard">
                <div class="wizard-inner">
                   <div class="connecting-line"></div>
                   <ul class="nav nav-tabs" role="tablist">
                      <li role="presentation" class="active">
                         <a href="#step1" data-toggle="tab" aria-controls="step1" role="tab" title="Profile">
                            <span class="round-tab">
                               <i class="glyphicon glyphicon-user" style="margin-right: 0px;"></i>
                           </span>
                       </a>
                   </li>
                   <li role="presentation" class="disabled">
                       <a href="#step2" data-toggle="tab" aria-controls="step2" role="tab" title="Emergency Contact">
                          <span class="round-tab">
                             <i class="glyphicon glyphicon-user" style="margin-right: 0px;"></i>
                         </span>
                     </a>
                 </li>                  
             </ul>
         </div>
         <div class="container" id="edit-profile" >
           <div class="row">
              <div class="col-lg-12 col-lg-offset-6 center-block" style="width: 500px; position: relative; left: 325px;" > 
                 <%= form_for(@user) do |form| %>
                 <div class="tab-content">
                    <div class="tab-pane active" role="tabpanel" id="step1">
                       <h3>Profile</h3>

                       <label class="col-xs-4 sr-only"></label>
                       <b>First Name: </b>
                       <%= form.text_field :first_name, class:"form-control", placeholder:"Enter your first name" %></br>

                       <label class="col-xs-4 sr-only">Last Name</label>
                       <b>Last Name: </b> 
                       <%= form.text_field :last_name ,class:"form-control", placeholder:"Enter your last name" %></br>

                       <label class="col-xs-4 sr-only">Biography</label>
                       <b>Biography: </b> 
                       <%= form.text_area :bio ,class:"form-control", placeholder:"Tell us more about yourself" %></br>

                       <label class="col-xs-4 sr-only">Interests</label>
                       <b>Interests: </b> 
                       <%= form.text_area :interests ,class:"form-control", placeholder:"What are some of your interests?" %></br>

                       <label class="col-xs-4 sr-only">Birthdate</label>
                       <b>Birthdate: </b> 
                       <%= form.date_field :birthdate ,class:"form-control", placeholder:"Birthday" %></br>

                       <label class="col-xs-4 sr-only">Location</label>
                       <b>Current Location: </b> 
                       <%= form.text_area :address ,class:"form-control", placeholder:"Where are you right now?" %></br>

                       <b>Email: </b> 
                       <label class="col-xs-4 sr-only"> Email</label>
                       <%= form.text_field :email, class:"form-control", placeholder:"Email"%></br> 

                      <label class="col-xs-4 sr-only">Travel Hacks</label>
                      <b>Travel Hacks: </b> 
                      <%= form.text_area :tips, class:"form-control", placeholder:"Any tips/recommendations for fellow travellers?"%></br>

                      <label class="col-xs-4 sr-only"> Favourite Destinations</label>
                      <b>Favourite Destinations: </b> 
                      <%= form.text_area :faves, class:"form-control", placeholder:"Where are some of your favourite holiday destinations?"%></br>           

                       <b>Profile Picture: </b>
                       <label class="sr-only" > Avatar</label>
                       <%= form.file_field :avatar %>

                       <ul class="list-inline pull-right" style="text-align: center;">
                          <li style="padding-right: 405px"><button type="button" class="btn btn-primary next-step">Next</button></li>
                      </ul>
                  </div>

                  <div class="tab-pane" role="tabpanel" id="step2">
                     <h3>Emergency Contact Information</h3>
                     <label class="sr-only">First Name</label>
                     <b>First Name: </b> 
                     <%= form.text_field :emer_first ,class:"form-control", placeholder:"First Name" %></br>

                     <label class="sr-only">Last Name</label>
                     <b>Last Name: </b> 
                     <%= form.text_field :emer_last ,class:"form-control", placeholder:"Last Name" %></br>

                     <label class="sr-only">Address</label>
                     <b>Address: </b> 
                     <%= form.text_area :emer_address ,class:"form-control", placeholder:"Address" %></br>

                     <label class="sr-only">Phone Number</label>
                     <b>Phone Number: </b> 
                     <%= form.telephone_field :emer_phone ,class:"form-control" %></br>

                     <div class="dropdown">
                        <button class="btn btn-default dropdown-toggle sr-only" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                           <span class="caret"></span>
                       </button>
                       <b>Relation: </b>
                       <ul>
                           <li><%= form.select :emer_relation,
                              [['Parents','Parents'],['Spouse','Spouse'],
                              ['Sibling','Sibling'],['Children','Children'],
                              ['Friend','Friend'],['Others','Others']] ,class:"form-control" ,class:"dropdown-menu" ,'aria-labelledby':"dropdownMenu1"%>
                          </li>
                      </ul>
                  </div>

                  <ul class="list-inline pull-right">
                      <li style="padding-right: 200px"><button type="button" class="btn btn-default prev-step">Previous</button></li>
                      <li style="padding-right: 200px"><%= form.submit "Save and Continue", class: "btn btn-primary btn-info-full next-step" %></button></li>
                      <% end %>
                  </ul>

              </div>
              <div class="clearfix"></div>
          </div>
      </div>
  </div>
</div>
</div>
</section>
</div>
</div>


</ul>

<div id="friends">
    <!-- put it here onwards -->
    <div class="container Container1">
      <div class="Content Wrapper">
            <div class="col-md-6">
            <!--  -->
              <% if current_user == @user && @user.requested_friendships.count != 0 %>
                <h4>Friend Requests</h4>
                <ul>
                  <% @user.requested_friendships.each do |request| %>
                  <% @user.friendships.each do |friendship| %>
                    <% if !friendship.original %>
                       <li>
                       <%= request.first_name %> <%= request.last_name %> 
                       <%= link_to "Accept", friendship_path(request.id), :method => "put" %> 
                       <%= link_to "Decline", friendship_path(request.id), :method => :delete %>
                       </li> 
                    <% end %> 
                   <% end %>   
                  <% end %>
                </ul>
              <% end %>
            <!--  -->
            <h4 class="header">Friends</h4>
              <% @user_friends.each do |f|%>
             
                   <div class="contact-cards-index-page">
                    <div class="row">
                        <div class="col-xs-3" >
                              <%= image_tag f.avatar, class: "img-responsive" %>                    
                        </div>
                        <div class="col-xs-6" style='padding-left: 5px;' >
                              <h3 style='margin: 0px;' >
                                    <%= link_to [f.first_name, f.last_name].join(" "), user_path(f.id) %>                                  
                              </h3>
                              <p>
                                <%= f.address %>

                                <%= f.interests %>
                              </p>                            
                        </div>
                        <div class="col-xs-3 removePadding" style='text-align: right;'>

                          <% if current_user %>

                            <%= link_to "             View Profile           ", user_path(f.id), class: "btn btn-success btn-xs"  %>
                            <br>

                            <%= link_to "Send Message", "#", class: "btn btn-success btn-xs start-conversation", "data-sid" => current_user.id, "data-rip" => f.id %>
                            <br>

                            <% unless @user != current_user %>
                                 
                            <%= link_to "Unfriend", friendship_path(f.id), class: "btn btn-success btn-xs", :method => :delete %>

                            <% end %>

                          <%else%>

                              <%= link_to " Login to View", "/", class: "btn btn-success btn-xs"  %>
                          <%end%>
                        </div>
                      </div>
                  </div>
              <%end%> 
            </div>

            <div class="col-md-6 right" >
              <!-- Your second column here -->


              <div style='width: 100%; height: 100%; '>
                <div id="map" style='width: 100%; height: 800px;'></div>
              </div>
            </div>
      </div>
    </div>


     
   <!-- stop here -->
</div>

<div id="reviews">
   <h4 class="header">Reviews</h4>
   
   <% if current_user.id != @user.id%>
   <%= render partial: 'reviews/form', locals: { user: @user } %>
   <%end%> 

   <table>
      <thead>
         <tr>
            <th>Comment</th>
            <th>Star</th>
            <th>User</th>
            <th colspan="3"></th>
        </tr>
    </thead>
    
        <% @reviews.each do |review| %>
        <tr>
           <td><%= review.comment %></td>
           <td class="stars" id="<%= review.id %>"></td>
         <td><%= review.user.first_name %></td>
         <td><%= link_to 'Edit', edit_user_review_path(@user, review.id) %></td>
         <td><%= link_to 'Destroy', user_review_path(@user.id, review.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <script>
            $("#<%= review.id %>.stars").raty({
               path: '/assets',
               readOnly: true,
               score: <%= review.star %>
           });
        </script>
        <% end %>
</div>
</div>
</div>




<script type="text/javascript">

  $(document).ready(function(){
    $('.map').hide()
  });
  $(document).on('page:change', function () {
      //Initialize tooltips
      $('.nav-tabs > li a[title]').tooltip();
      
      //Wizard
      $('a[data-toggle="tab"]').on('show.bs.tab', function (e) {

         var $target = $(e.target);

         if ($target.parent().hasClass('disabled')) {
            return false;
        }
    });

      $(".next-step").click(function (e) {
         var $active = $('.wizard .nav-tabs li.active');
         $active.next().removeClass('disabled');
         nextTab($active);
         $('.map').show();

     });
      $(".prev-step").click(function (e) {

         var $active = $('.wizard .nav-tabs li.active');
         prevTab($active);
         $('.map').hide();

     });
  });

</script>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: "map"}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>